try {
    /** Permite  */
    throw "Error de programa"
    let x = noExiste()

} catch (error) {
   // console.log('noooo')
    alert(error)
}






















